## Spring application configuration
#spring:
#  application:
#    name: JAVA_PROJECT
#
#  data:
#    mongodb:
#      uri: "mongodb+srv://shahzaibarain0080:ibQIMOQIcYvNYdkt@cluster0.1xuxr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
#      database: applicationdb
#      auto-index-creation: true
#
#  main:
#    allow-circular-references: false
#
#server:
#  port: 8081
#  servlet:
#    context-path: /User
