#spring:
#  application:
#    name: JAVA_PROJECT
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/applicationdb
#      database: applicationdb
#      auto-index-creation: true
#  main:
#    allow-circular-references: true
#weather:
#  api:
#    key: c8b8e70c6a3858b8edb9870d4213de39
